# Generated by Django 3.2.10 on 2021-12-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=255, verbose_name='Video Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('published_on', models.DateTimeField(verbose_name='publishing datetime')),
                ('thumb_url', models.URLField(help_text='The URL to the video thumbnail', max_length=255, verbose_name='Thumbnail URL')),
                ('link', models.URLField(help_text='The URL to the video page', max_length=255, verbose_name='Video Link')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
                'ordering': ['-published_on'],
            },
        ),
    ]
